onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /RotateDatapath_tb/Zout
add wave -noupdate /RotateDatapath_tb/R0out
add wave -noupdate /RotateDatapath_tb/R1out
add wave -noupdate /RotateDatapath_tb/R2out
add wave -noupdate /RotateDatapath_tb/R3out
add wave -noupdate /RotateDatapath_tb/R4out
add wave -noupdate /RotateDatapath_tb/R5out
add wave -noupdate /RotateDatapath_tb/R6out
add wave -noupdate /RotateDatapath_tb/R7out
add wave -noupdate /RotateDatapath_tb/R8out
add wave -noupdate /RotateDatapath_tb/R9out
add wave -noupdate /RotateDatapath_tb/R10out
add wave -noupdate /RotateDatapath_tb/R11out
add wave -noupdate /RotateDatapath_tb/R12out
add wave -noupdate /RotateDatapath_tb/R13out
add wave -noupdate /RotateDatapath_tb/R14out
add wave -noupdate /RotateDatapath_tb/R15out
add wave -noupdate /RotateDatapath_tb/HIout
add wave -noupdate /RotateDatapath_tb/LOout
add wave -noupdate /RotateDatapath_tb/Zhighout
add wave -noupdate /RotateDatapath_tb/Zlowout
add wave -noupdate /RotateDatapath_tb/PCout
add wave -noupdate /RotateDatapath_tb/MDRout
add wave -noupdate /RotateDatapath_tb/InPortout
add wave -noupdate /RotateDatapath_tb/Cout
add wave -noupdate /RotateDatapath_tb/MARin
add wave -noupdate /RotateDatapath_tb/Zin
add wave -noupdate /RotateDatapath_tb/PCin
add wave -noupdate /RotateDatapath_tb/MDRin
add wave -noupdate /RotateDatapath_tb/IRin
add wave -noupdate /RotateDatapath_tb/Yin
add wave -noupdate /RotateDatapath_tb/HIin
add wave -noupdate /RotateDatapath_tb/LOin
add wave -noupdate /RotateDatapath_tb/IncPC
add wave -noupdate /RotateDatapath_tb/Read
add wave -noupdate /RotateDatapath_tb/R0in
add wave -noupdate /RotateDatapath_tb/R1in
add wave -noupdate /RotateDatapath_tb/R2in
add wave -noupdate /RotateDatapath_tb/R3in
add wave -noupdate /RotateDatapath_tb/R4in
add wave -noupdate /RotateDatapath_tb/R5in
add wave -noupdate /RotateDatapath_tb/R6in
add wave -noupdate /RotateDatapath_tb/R7in
add wave -noupdate /RotateDatapath_tb/R8in
add wave -noupdate /RotateDatapath_tb/R9in
add wave -noupdate /RotateDatapath_tb/R10in
add wave -noupdate /RotateDatapath_tb/R11in
add wave -noupdate /RotateDatapath_tb/R12in
add wave -noupdate /RotateDatapath_tb/R13in
add wave -noupdate /RotateDatapath_tb/R14in
add wave -noupdate /RotateDatapath_tb/R15in
add wave -noupdate /RotateDatapath_tb/ZhighIn
add wave -noupdate /RotateDatapath_tb/ZlowIn
add wave -noupdate /RotateDatapath_tb/clock
add wave -noupdate /RotateDatapath_tb/clear
add wave -noupdate /RotateDatapath_tb/opcode
add wave -noupdate /RotateDatapath_tb/Mdatain
add wave -noupdate /RotateDatapath_tb/Present_state
add wave -noupdate /RotateDatapath_tb/DUT/R3/q
add wave -noupdate /RotateDatapath_tb/DUT/R7/q
add wave -noupdate /RotateDatapath_tb/DUT/R4/q
add wave -noupdate /RotateDatapath_tb/DUT/PC/q
add wave -noupdate /RotateDatapath_tb/DUT/IR/q
add wave -noupdate /RotateDatapath_tb/DUT/ZLow/q
add wave -noupdate /RotateDatapath_tb/DUT/LO/q
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {499131 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 224
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {31778 ps} {525695 ps}
